env:
  es2021: true
  node: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
extends: ["prettier", 'plugin:@typescript-eslint/recommended']
plugins: ["prettier", '@typescript-eslint']
rules:
  prettier/prettier: ["error"]
parser: '@typescript-eslint/parser'
